<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Change</name>
   <tag></tag>
   <elementGuidId>68e41065-1436-4da8-8e5f-1c20cbf0bc1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-flyout-icp']/div[2]/span[3]/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.icp-flyout-change</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9ea9379c-3732-4577-bc65-0f3c6a820351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/customer-preferences/edit?ref_=icp_cop_flyout_change&amp;preferencesReturnUrl=%2Fs%3Fk%3Dthermometer%26crid%3D3NOH61GD9E5VK%26sprefix%3Dthermometer%252Caps%252C337%26ref%3Dnb_sb_noss_1</value>
      <webElementGuid>9e8d0b3e-cdd1-4f5b-af69-8176c02fd806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icp-flyout-change</value>
      <webElementGuid>55f35e8f-c962-49a6-8b62-a6d271db5a05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Change</value>
      <webElementGuid>3a7416a3-54a8-4ff4-aed4-973e24223789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-flyout-icp&quot;)/div[@class=&quot;nav-template nav-flyout-content nav-tpl-itemList&quot;]/span[@class=&quot;nav-item&quot;]/span[@class=&quot;nav-text&quot;]/a[@class=&quot;icp-flyout-change&quot;]</value>
      <webElementGuid>b723c741-0e12-448d-aeda-85060a0185f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-flyout-icp']/div[2]/span[3]/span/a</value>
      <webElementGuid>58f569de-2278-4753-8a36-bdbfdcbccaef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Change')]</value>
      <webElementGuid>e68e8457-61c1-41ce-853e-9c507dc9d447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/customer-preferences/edit?ref_=icp_cop_flyout_change&amp;preferencesReturnUrl=%2Fs%3Fk%3Dthermometer%26crid%3D3NOH61GD9E5VK%26sprefix%3Dthermometer%252Caps%252C337%26ref%3Dnb_sb_noss_1')]</value>
      <webElementGuid>194f009e-82ee-4131-9cce-23a4056d124b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/span/a</value>
      <webElementGuid>14ba8549-0419-47c1-9ddf-907d2398ef97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/customer-preferences/edit?ref_=icp_cop_flyout_change&amp;preferencesReturnUrl=%2Fs%3Fk%3Dthermometer%26crid%3D3NOH61GD9E5VK%26sprefix%3Dthermometer%252Caps%252C337%26ref%3Dnb_sb_noss_1' and (text() = 'Change' or . = 'Change')]</value>
      <webElementGuid>d0ec6ab9-a9a4-4d1f-9cbd-4f6c7507d22f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
