<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_submit.gc-add-to-cart</name>
   <tag></tag>
   <elementGuidId>56fce55e-3a14-4594-b24f-d2c8d12687dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gc-buy-box-atc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gc-buy-box-atc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7b0cd8dc-36e0-465b-ab22-ff60e0588dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gc-buy-box-atc</value>
      <webElementGuid>45012851-bf3b-451d-98f4-82cb70a0d936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit.gc-add-to-cart</value>
      <webElementGuid>81ed76a7-fc28-4848-8b68-a6f9bbbfc1e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input gc-buy-box-disabled</value>
      <webElementGuid>62feb41f-e99f-45d1-9864-778cf8821304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e86eeebe-0001-4457-b79b-f00a1b5add30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>a-autoid-0-announce</value>
      <webElementGuid>4289f9b3-b74d-468b-a934-0e1b23751393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gc-buy-box-atc&quot;)</value>
      <webElementGuid>878bd292-d6e1-4206-adf9-3edd8da9c709</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gc-buy-box-atc']</value>
      <webElementGuid>176ed9a0-19fc-4f0a-a770-f4a1f17a1d3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='a-autoid-0']/span/input</value>
      <webElementGuid>83521ee4-ef10-4340-8995-5e45583dba11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/input</value>
      <webElementGuid>f11c0a44-acec-4859-ad98-f37b58b718cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'gc-buy-box-atc' and @name = 'submit.gc-add-to-cart' and @type = 'submit']</value>
      <webElementGuid>95efbcef-879b-4650-96b0-0c8c00bb3567</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
