<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Deselect all items</name>
   <tag></tag>
   <elementGuidId>05abdf19-1491-4f90-a9f0-0c7055e9093b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#deselect-all</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='deselect-all']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d6184f2a-9308-4a24-a017-061832b0adb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>deselect-all</value>
      <webElementGuid>52964a9d-beae-4df1-9916-80f307314d49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-link-normal sc-selection-state-update</value>
      <webElementGuid>ae510125-9838-4033-98c1-7b611672e869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>47b80cca-562c-4ce0-b199-830a2ea47ea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                  Deselect all items
                              </value>
      <webElementGuid>32f60b92-7cfd-430b-b50b-14b2f9feaacb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;deselect-all&quot;)</value>
      <webElementGuid>d731e0b5-3b18-4045-9533-ddc16a2942e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='deselect-all']</value>
      <webElementGuid>cf55ff14-8bd3-4123-bb8e-6bd022128750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sc-active-cart']/div/div/div[2]/a</value>
      <webElementGuid>21074605-bf06-423b-9100-cdf9f0098b3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Deselect all items')]</value>
      <webElementGuid>e807b974-fc5d-4338-904a-810af90e1dd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>d96bff3c-a201-4239-87f1-6520df58b694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/a</value>
      <webElementGuid>5c081233-9cb3-477f-87e7-25466c06f4bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'deselect-all' and @href = '#' and (text() = '
                                  Deselect all items
                              ' or . = '
                                  Deselect all items
                              ')]</value>
      <webElementGuid>44107e65-214b-4a57-ab99-3202b2814b8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
