<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_submit.deleteItem</name>
   <tag></tag>
   <elementGuidId>6e4fcefc-ae8f-4d5c-a740-dfe996393a78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='submit.deleteItem']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;submit.deleteItem&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>43b59030-4ef4-4e8f-9070-d863f8e5bd92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit.deleteItem</value>
      <webElementGuid>d6e038e1-5015-487c-80f0-9ef5b52d39e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-action</name>
      <type>Main</type>
      <value>sab:list_c_wl_lv_ov_lig_itemDelete</value>
      <webElementGuid>888a3a66-5833-40be-b77e-d1ae150e763a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-item-id</name>
      <type>Main</type>
      <value>B084W9Y7HP</value>
      <webElementGuid>f4e9f767-bafd-4dd9-aeb9-b82fac698237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>action</value>
      <webElementGuid>76235844-5322-482c-92d0-922b66cf9a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input a-declarative</value>
      <webElementGuid>7ee62c19-9b0d-4f0d-b89a-a4f066004a8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>46c67873-8e03-404f-9d4d-19e9b5ef895d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>delete-button-IJKIOXQBJ0SXJ-announce</value>
      <webElementGuid>fcdcc15f-12a9-4a1f-b494-a8977b23626f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>fhl3j8-mskua9-gp9nzn-p6dqja</value>
      <webElementGuid>0bddfd63-cce5-4813-9e4e-4b75739c9a97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delete-button-IJKIOXQBJ0SXJ&quot;)/span[@class=&quot;a-button-inner&quot;]/input[@class=&quot;a-button-input a-declarative&quot;]</value>
      <webElementGuid>9ccb6ed1-04dc-427a-a8db-b85d60d643a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='submit.deleteItem']</value>
      <webElementGuid>0df911bb-9101-4bbb-ba9b-8c4ca207ba30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='delete-button-IJKIOXQBJ0SXJ']/span/input</value>
      <webElementGuid>7864e210-74a9-4188-898d-3942dddee167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/span/span/span/input</value>
      <webElementGuid>932e869f-95d1-40c9-b0f2-7737c359bf17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'submit.deleteItem' and @type = 'submit']</value>
      <webElementGuid>7c297003-641a-46c1-a421-f4f466310f32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
