<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_thermometer</name>
   <tag></tag>
   <elementGuidId>3bf3c1ae-f249-476c-b64b-0a2cde2b1f3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-flyout-searchAjax']/div[2]/div/div/div[4]/div/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(4) > div.s-suggestion-trending-container > div.s-suggestion-trending.s-suggestion-ellipsis-direction > span.s-heavy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>995647e3-5046-43af-98e6-76a299206d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>s-heavy</value>
      <webElementGuid>596c3111-a4eb-4559-b517-3224505c82f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>thermometer</value>
      <webElementGuid>c1cb4a97-a156-4b1b-a17e-b54f53e4cf88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-flyout-searchAjax&quot;)/div[@class=&quot;autocomplete-results-container&quot;]/div[@class=&quot;two-pane-results-container&quot;]/div[@class=&quot;left-pane-results-container&quot;]/div[4]/div[@class=&quot;s-suggestion-trending-container&quot;]/div[@class=&quot;s-suggestion-trending s-suggestion-ellipsis-direction&quot;]/span[@class=&quot;s-heavy&quot;]</value>
      <webElementGuid>9355c4df-d889-478f-a246-544fbcaf6ab8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-flyout-searchAjax']/div[2]/div/div/div[4]/div/div[2]/span</value>
      <webElementGuid>c3b537b7-47ad-483a-9a0c-da7df865bfd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/span</value>
      <webElementGuid>c027bb41-a0fd-47d1-a51b-54ce905dab42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'thermometer' or . = 'thermometer')]</value>
      <webElementGuid>588d0756-48eb-4c3c-adb5-a05c3a463747</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
