<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Add to List</name>
   <tag></tag>
   <elementGuidId>2236116f-f4cb-41b8-963f-5d7f78505c1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h4[@id='a-popover-header-3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#a-popover-header-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>f2d15a8e-0904-42bc-9623-7ba1f2a22915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-popover-header-content</value>
      <webElementGuid>8f3364fd-bda0-4440-8589-dec7590d08d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a-popover-header-3</value>
      <webElementGuid>03f9db8e-110a-4775-8292-d26d263fe93c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add to List</value>
      <webElementGuid>7d7112fd-44fe-493e-a375-96350bde36ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-popover-header-3&quot;)</value>
      <webElementGuid>bc66c350-1e96-4c5a-9d8e-ecd0837ef36d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h4[@id='a-popover-header-3']</value>
      <webElementGuid>27fa966f-763c-4699-a677-c82317386174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a-popover-3']/div/header/h4</value>
      <webElementGuid>a56ede20-63f8-42eb-9555-642cadc74d39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/h4</value>
      <webElementGuid>a0ec876c-9e1d-4a0a-b060-e921d0796413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[@id = 'a-popover-header-3' and (text() = 'Add to List' or . = 'Add to List')]</value>
      <webElementGuid>960776f1-6b57-415a-a64a-b4263a758f41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
