<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_submit.add-to-registry.wishlist</name>
   <tag></tag>
   <elementGuidId>adb1ab5c-39e4-460a-bfdc-b8b4ccbfe31b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='add-to-wishlist-button-submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#add-to-wishlist-button-submit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5b5560d1-9f9f-4f06-acae-12c0c1254d51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-to-wishlist-button-submit</value>
      <webElementGuid>6837934c-2e94-4cc8-83cd-9dd69c079f93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit.add-to-registry.wishlist</value>
      <webElementGuid>67a8877c-392d-4991-bfd4-69151a4f0232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add to List</value>
      <webElementGuid>83c204e1-b842-4c1e-a041-144aa90c4b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>atwl-splitbutton-main</value>
      <webElementGuid>8625fb24-de1b-4893-bd02-02e403909818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hover</name>
      <type>Main</type>
      <value>&lt;!-- If PartialItemStateWeblab is true then, showing different Add-to-wish-list tool-tip message which is consistent with Add-to-Cart tool tip message.  -->
       To Add to Your List, choose from options to the left</value>
      <webElementGuid>80736bab-c6dd-4dcc-8223-f879d73457cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input a-declarative</value>
      <webElementGuid>d529578b-f720-4465-a8e6-0dbe466af06b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>cbd27ab3-3c35-4b6c-bddf-72c81c837ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Add to List</value>
      <webElementGuid>aecc9ae7-e38c-41d1-9b37-fba109601eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>wishListMainButton-announce</value>
      <webElementGuid>17a905c2-e82b-498a-8f70-734e4fe08a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-to-wishlist-button-submit&quot;)</value>
      <webElementGuid>28c59bd2-4a14-435e-87e7-7516a491372d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='add-to-wishlist-button-submit']</value>
      <webElementGuid>2767b69a-23b6-4219-8a38-c948e5168ee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='wishListMainButton']/span/input</value>
      <webElementGuid>51503089-e8e9-4af4-a0f2-336641871473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span/span/input</value>
      <webElementGuid>4253dd69-9f26-48f4-8c7c-f7f83fadf37b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'add-to-wishlist-button-submit' and @name = 'submit.add-to-registry.wishlist' and @title = 'Add to List' and @type = 'submit']</value>
      <webElementGuid>5ec772bd-1f8c-481f-ad4d-08632980606e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
