<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View Your List</name>
   <tag></tag>
   <elementGuidId>78483603-50c9-4e49-9ec2-e52f70970c75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='huc-view-your-list-button']/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.a-button-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c3c059ef-3032-4200-b220-e2730c4ccc52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.amazon.com/hz/wishlist/ls/1B2DV3JD0CHZZ?ref_=wl_dp_view_your_list</value>
      <webElementGuid>09489775-695f-4648-89f3-10d5c78b7618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-text</value>
      <webElementGuid>1e973668-60b5-4dcf-9f96-212862f88e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Your List</value>
      <webElementGuid>87014d15-49e9-4be3-96fc-317d6dcd371c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;huc-view-your-list-button&quot;)/span[@class=&quot;a-button-inner&quot;]/a[@class=&quot;a-button-text&quot;]</value>
      <webElementGuid>dc9ae50a-3214-467c-a61c-99a85234ce7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='huc-view-your-list-button']/span/a</value>
      <webElementGuid>59ac1ee2-4a5b-4e01-a6fa-299826f9ce82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View Your List')]</value>
      <webElementGuid>37808794-28d0-4cca-a04e-3ec911747544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.amazon.com/hz/wishlist/ls/1B2DV3JD0CHZZ?ref_=wl_dp_view_your_list')]</value>
      <webElementGuid>ba34a7a8-650a-4e7a-ac3c-d0d40f4d4f66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/span/span/a</value>
      <webElementGuid>95df3c48-7202-490f-8032-c0b4e1daa019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.amazon.com/hz/wishlist/ls/1B2DV3JD0CHZZ?ref_=wl_dp_view_your_list' and (text() = 'View Your List' or . = 'View Your List')]</value>
      <webElementGuid>9e1a2d66-7c86-4f5e-a7ed-ed665ecbbca7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
